version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: codeception/codeception
    versions:
    - 4.1.16
    - 4.1.17
    - 4.1.18
    - 4.1.19
  - dependency-name: nesbot/carbon
    versions:
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: tightenco/collect
    versions:
    - 8.19.0
